[platformio]
workspace_dir = /Users/hwaipy/Documents/PlatformIO/ESP32Framework/app/Recorder
build_dir = /Users/hwaipy/Documents/PlatformIO/ESP32Framework/app/Recorder/build
libdeps_dir = /Users/hwaipy/Documents/PlatformIO/ESP32Framework/app/Recorder/libdeps
cache_dir = /Users/hwaipy/Documents/PlatformIO/ESP32Framework/cache
default_envs =
    esp32-s3-supermini

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@7.4.3
lib_extra_dirs =
    ${platformio.workspace_dir}/vendor
extra_scripts =
    pre:fetch_usb_host_uac.py

board_upload.flash_size = 4MB
board_build.flash_size = 4MB
board_build.partitions = default.csv

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DBOARD_HAS_PSRAM
    -DCONFIG_UAC_DEV_ADDR_LIST_MAX=6
    -DCONFIG_UAC_FREQ_NUM_MAX=4
    -DCONFIG_UAC_NUM_ISOC_URBS=3
    -DCONFIG_UAC_NUM_PACKETS_PER_URB=3
    -DCONFIG_UAC_RINGBUF_SAFE_DELETE_WAITING_MS=50
    -DUSB_HOST_UAC_VER_MAJOR=1
    -DUSB_HOST_UAC_VER_MINOR=5
    -DUSB_HOST_UAC_VER_PATCH=0
    -I../../base/include

[env:esp32-s3-supermini]
board = esp32-s3-devkitc-1
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_qspi
